### ISSUE TITLE
Doesn't work as described

### ISSUE THREAD

**Issue by kyds3k** [reaby/obs-serato#1]
This had me excited:

> Now playing info is updated in delay of 1 song.
>This means:
>1. Deck1 load Song1
>   * now playing: Song1
>2. Deck2 load Song2
>   * now playing: Song1
>3. Deck1 load Song3 
 >  * now playing: Song2
>
>If you wish to update song as of instant, just 
>press eject of non-loaded song:
>
>1. Deck1 load Song1
 >  * now playing: Song1
>2. Deck2 load Song2
 >  * Press eject on deck1
 >  * now playing: Song2
>3. Deck1 load Song3 
 >  * Press eject on deck2
 >  * now playing: Song3

However, I find that the track name changes as soon as I load a new track anywhere - and if I eject the track that is says is now playing, I get blank info. Can you help?

**Comment by reaby** [comment]
Dunno, might there been some update with the serato lately that changes the data strucure of the history file? That's how it been working by this far. I can try to see if there's update for the demo, it's all i have for serato :) Anyway I wrote the app for my DJ friend and it works for him just fine. Dunno if you do something differently while DJ'ing or has there indeed been some update for the datastructure of the history file... I try to find time to update and check soonish, meanwhile it's typescript and I see from your profile you're a webdev, so maybe while waiting you can add some debug points and see where the datastructure fails for your usecase as this is mainly a web app after all :)

**Comment by reaby** [comment]
I had really old version of the lite, but even with the newest one it works as intented.

**Comment by kyds3k** [comment]
I'll try and take a look when I get a chance! Thanks for the reply :-D

**Comment by reaby** [comment]
Cool! Hopefully you get it working with your use-case as well! 
I close the ticket, since I find it works in-a-way it works for our need.
